from gym.envs.face_seacher.face_seacher_game import FaceSeacherEnv
from gym.envs.face_seacher.face_seacher_game_v2 import FaceSeacherEnv_v2
from gym.envs.face_seacher.face_seacher_game_v3 import FaceSeacherEnv_v3